# Generated by Django 6.0.1 on 2026-03-14

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userpreference",
            name="free_shipping_updates",
        ),
        migrations.RemoveField(
            model_name="userpreference",
            name="is_adult",
        ),
        migrations.RemoveField(
            model_name="userpreference",
            name="promo_opt_in",
        ),
    ]
