# Generated by Django 6.0.1 on 2026-03-14

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0002_remove_userpreference_free_shipping_updates_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="UserPreference",
        ),
    ]
