# Generated by Django 6.0.1 on 2026-04-07 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('manager', 'Manager'), ('shop_owner', 'Shop Owner'), ('customer', 'Customer')], default='customer', max_length=20),
        ),
    ]
