# Generated by Django 6.0.1 on 2026-03-09 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='item_image',
            field=models.ImageField(default='images/default.jpg', upload_to='images/'),
        ),
    ]
